
from tft_composition_finder.schemas.champion import Champion

TFT_CHAMPIONS = [
    Champion(name="Aatrox", traits={"bruiser", "ghostly", "inkshadow"}, cost=2, damage_type="magic"),
    Champion(name="Ahri", traits={"arcanist", "fated"}, cost=1, damage_type="magic"),
    Champion(name="Alune", traits={"invoker", "umbral"}, cost=3, damage_type="magic"),
    Champion(name="Amumu", traits={"porcelain", "warden"}, cost=3, damage_type="magic"),
    Champion(name="Annie", traits={"fortune", "invoker"}, cost=4, damage_type="magic"),
    Champion(name="Aphelios", traits={"fated", "sniper"}, cost=3, damage_type="physical"),
    Champion(name="Ashe", traits={"porcelain", "sniper"}, cost=4, damage_type="physical"),
    Champion(name="Azir", traits={"dryad", "invoker"}, cost=5, damage_type="magic"),
    Champion(name="Bard", traits={"mythic", "trickshot"}, cost=3, damage_type="mixed"),
    Champion(name="Caitlyn", traits={"ghostly", "sniper"}, cost=1, damage_type="physical"),
    Champion(name="Cho'gath", traits={"behemoth", "mythic"}, cost=1, damage_type="magic"),
    Champion(name="Darius", traits={"duelist", "umbral"}, cost=1, damage_type="magic"),
    Champion(name="Diana", traits={"dragonlord", "sage"}, cost=3, damage_type="magic"),
    Champion(name="Galio", traits={"bruiser", "storyweaver"}, cost=4, damage_type="magic"),
    Champion(name="Garen", traits={"storyweaver", "warden"}, cost=1, damage_type="physical"),
    Champion(name="Gnar", traits={"dryad", "warden"}, cost=2, damage_type="physical"),
    Champion(name="Hwei", traits={"artist", "mythic"}, cost=5, damage_type="magic"),
    Champion(name="Illaoi", traits={"arcanist", "ghostly", "warden"}, cost=3, damage_type="magic"),
    Champion(name="Irelia", traits={"duelist", "storyweaver"}, cost=5, damage_type="physical"),
    Champion(name="Janna", traits={"dragonlord", "invoker"}, cost=2, damage_type="magic"),
    Champion(name="Jax", traits={"inkshadow", "warden"}, cost=1, damage_type="magic"),
    Champion(name="Kai'sa", traits={"inkshadow", "trickshot"}, cost=4, damage_type="physical"),
    Champion(name="Kayn", traits={"ghostly", "reaper"}, cost=4, damage_type="physical"),
    Champion(name="Kha'zix", traits={"heavenly", "reaper"}, cost=1, damage_type="physical"),
    Champion(name="Kindred", traits={"dryad", "fated", "reaper"}, cost=2, damage_type="magic"),
    Champion(name="Kobuko", traits={"bruiser", "fortune"}, cost=1, damage_type="magic"),
    Champion(name="Kog'maw", traits={"invoker", "mythic", "sniper"}, cost=1, damage_type="magic"),
    Champion(name="Lee Sin", traits={"dragonlord", "duelist"}, cost=4, damage_type="physical"),
    Champion(name="Lillia", traits={"invoker", "mythic"}, cost=4, damage_type="magic"),
    Champion(name="Lissandra", traits={"arcanist", "porcelain"}, cost=5, damage_type="magic"),
    Champion(name="Lux", traits={"arcanist", "porcelain"}, cost=2, damage_type="magic"),
    Champion(name="Malphite", traits={"behemoth", "heavenly"}, cost=1, damage_type="magic"),
    Champion(name="Morgana", traits={"ghostly", "sage"}, cost=4, damage_type="magic"),
    Champion(name="Nautilus", traits={"mythic", "warden"}, cost=4, damage_type="magic"),
    Champion(name="Neeko", traits={"arcanist", "heavenly", "mythic"}, cost=2, damage_type="magic"),
    Champion(name="Ornn", traits={"behemoth", "dryad"}, cost=4, damage_type="magic"),
    Champion(name="Qiyana", traits={"duelist", "heavenly"}, cost=2, damage_type="physical"),
    Champion(name="Rakan", traits={"altruist", "dragonlord", "lovers"}, cost=5, damage_type="magic"),
    Champion(name="Rek'sai", traits={"bruiser", "dryad"}, cost=1, damage_type="magic"),
    Champion(name="Riven", traits={"altruist", "bruiser", "storyweaver"}, cost=2, damage_type="physical"),
    Champion(name="Senna", traits={"inkshadow", "sniper"}, cost=2, damage_type="physical"),
    Champion(name="Sett", traits={"fated", "umbral", "warden"}, cost=5, damage_type="physical"),
    Champion(name="Shen", traits={"behemoth", "ghostly"}, cost=2, damage_type="mixed"),
    Champion(name="Sivir", traits={"storyweaver", "trickshot"}, cost=1, damage_type="physical"),
    Champion(name="Soraka", traits={"altruist", "heavenly"}, cost=3, damage_type="magic"),
    Champion(name="Sylas", traits={"bruiser", "umbral"}, cost=4, damage_type="magic"),
    Champion(name="Syndra", traits={"arcanist", "fated"}, cost=4, damage_type="magic"),
    Champion(name="Tahm Kench", traits={"bruiser", "mythic"}, cost=3, damage_type="magic"),
    Champion(name="Teemo", traits={"fortune", "trickshot"}, cost=2, damage_type="magic"),
    Champion(name="Thresh", traits={"behemoth", "fated"}, cost=3, damage_type="magic"),
    Champion(name="Tristana", traits={"duelist", "fortune"}, cost=3, damage_type="physical"),
    Champion(name="Udyr", traits={"behemoth", "inkshadow", "spirit walker"}, cost=5, damage_type="magic"),
    Champion(name="Volibear", traits={"duelist", "inkshadow"}, cost=3, damage_type="magic"),
    Champion(name="Wukong", traits={"great", "heavenly"}, cost=5, damage_type="physical"),
    Champion(name="Xayah", traits={"dragonlord", "lovers", "trickshot"}, cost=5, damage_type="physical"),
    Champion(name="Yasuo", traits={"duelist", "fated"}, cost=1, damage_type="magic"),
    Champion(name="Yone", traits={"reaper", "umbral"}, cost=3, damage_type="physical"),
    Champion(name="Yorick", traits={"behemoth", "umbral"}, cost=2, damage_type="magic"),
    Champion(name="Zoe", traits={"arcanist", "fortune", "storyweaver"}, cost=3, damage_type="magic"),
    Champion(name="Zyra", traits={"sage", "storyweaver"}, cost=2, damage_type="magic"),
]