from .set_12.champions import TFT_CHAMPIONS
from .set_12.traits import TRAIT_BREAKPOINTS, TRAIT_BREAKPOINTS_DICT
from .set_12.config import TRAIT_SCORE_WEIGHT, UNIT_SCORE, INCLUDE_CHAMPS, EXCLUDE_CHAMPS, INCLUDE_TRAITS, MIN_MAX_UNIT_BY_COST, MAX_ATTEMPTS, MIN_SCORE, MIN_TRAIT_LEVEL, MIN_DIFFERENT_TRAITS_PER_LEVEL