from typing import Literal

from tft_composition_finder.schemas.champion import Champion

TFT_CHAMPIONS = [
    Champion(name="Ahri", traits={"Arcana", "Scholar"}, cost=2, roles={"ap"}),
    Champion(name="Akali", traits={"Multistriker", "Warrior", "Pyro"}, cost=2, roles={"ap"}),
    Champion(name="Ashe", traits={"Eldritch", "Multistriker"}, cost=1, roles={"ad"}),
    Champion(name="Bard", traits={"Sugarcraft", "Preserver"}, cost=4, roles={"ap"}),
    Champion(name="Blitzcrank", traits={"Honeymancy", "Vanguard"}, cost=1, roles={"ad", "tank"}),
    Champion(name="Briar", traits={"Shapeshifter", "Eldritch", "Ravenous"}, cost=5, roles={"ad"}),
    Champion(name="Camille", traits={"Multistriker", "Chrono"}, cost=5, roles={"ad", "tank"}),
    Champion(name="Cassiopeia", traits={"Witchcraft", "Incantor"}, cost=2, roles={"ap"}),
    Champion(name="Diana", traits={"Bastion", "Frost"}, cost=5, roles={"ap", "tank"}),
    Champion(name="Elise", traits={"Shapeshifter", "Eldritch"}, cost=1, roles={"ap", "tank"}),
    Champion(name="Ezreal", traits={"Blaster", "Portal"}, cost=3, roles={"ap"}),
    Champion(name="Fiora", traits={"Witchcraft", "Warrior"}, cost=4, roles={"ad"}),
    Champion(name="Galio", traits={"Vanguard", "Mage", "Portal"}, cost=2, roles={"ap"}),
    Champion(name="Gwen", traits={"Warrior", "Sugarcraft"}, cost=4, roles={"ap"}),
    Champion(name="Hecarim", traits={"Bastion", "Portal"}, cost=3, roles={"ap"}),
    Champion(name="Hwei", traits={"Blaster", "Frost"}, cost=3, roles={"ad"}),
    Champion(name="Jax", traits={"Chrono", "Multistriker"}, cost=1, roles={"ad"}),
    Champion(name="Jayce", traits={"Shapeshifter", "Portal"}, cost=1, roles={"ad"}),
    Champion(name="Jinx", traits={"Hunter", "Sugarcraft"}, cost=3, roles={"ad"}),
    Champion(name="Kalista", traits={"Faerie", "Multistriker"}, cost=4, roles={"ad"}),
    Champion(name="Karma", traits={"Chrono", "Incantor"}, cost=4, roles={"ap"}),
    Champion(name="Kassadin", traits={"Multistriker", "Portal"}, cost=2, roles={"ap"}),
    Champion(name="Katarina", traits={"Faerie", "Warrior"}, cost=3, roles={"ad"}),
    Champion(name="Kogmaw", traits={"Honeymancy", "Hunter"}, cost=2, roles={"ad"}),
    Champion(name="Lillia", traits={"Bastion", "Faerie"}, cost=1, roles={"ap", "tank"}),
    Champion(name="Milio", traits={"Scholar", "Faerie"}, cost=5, roles={"ap"}),
    Champion(name="Mordekaiser", traits={"Vanguard", "Eldritch"}, cost=3, roles={"ap"}),
    Champion(name="Morgana", traits={"Witchcraft", "Preserver", "Bat Queen"}, cost=5, roles={"ap"}),
    Champion(name="Nami", traits={"Mage", "Eldritch"}, cost=4, roles={"ap"}),
    Champion(name="Nasus", traits={"Shapeshifter", "Pyro"}, cost=4, roles={"ap", "tank"}),
    Champion(name="Neeko", traits={"Witchcraft", "Shapeshifter"}, cost=3, roles={"ap", "tank"}),
    Champion(name="Nilah", traits={"Warrior", "Eldritch"}, cost=2, roles={"ad"}),
    Champion(name="Nomsy", traits={"Hunter", "Dragon"}, cost=1, roles={"ap"}),
    Champion(name="Norra", traits={"Explorer", "Mage", "Portal"}, cost=5, roles={"ap"}),
    Champion(name="Nunu", traits={"Bastion", "Honeymancy"}, cost=2, roles={"ap", "tank"}),
    Champion(name="Olaf", traits={"Hunter", "Frost"}, cost=4, roles={"ad"}),
    Champion(name="Poppy", traits={"Witchcraft", "Bastion"}, cost=1, roles={"ap"}),
    Champion(name="Rakan", traits={"Preserver", "Faerie"}, cost=4, roles={"ap", "tank"}),
    Champion(name="Rumble", traits={"Blaster", "Sugarcraft", "Vanguard"}, cost=2, roles={"ad"}),
    Champion(name="Ryze", traits={"Scholar", "Portal"}, cost=4, roles={"ap"}),
    Champion(name="Seraphine", traits={"Mage", "Faerie"}, cost=1, roles={"ap"}),
    Champion(name="Shen", traits={"Bastion", "Pyro"}, cost=3, roles={"ad", "tank"}),
    Champion(name="Shyvana", traits={"Shapeshifter", "Dragon"}, cost=2, roles={"ap"}),
    Champion(name="Smolder", traits={"Blaster", "Dragon"}, cost=5, roles={"ad"}),
    Champion(name="Soraka", traits={"Mage", "Sugarcraft"}, cost=1, roles={"ap"}),
    Champion(name="Swain", traits={"Shapeshifter", "Frost"}, cost=3, roles={"ap", "tank"}),
    Champion(name="Syndra", traits={"Incantor", "Eldritch"}, cost=2, roles={"ap"}),
    Champion(name="Tahm Kench", traits={"Vanguard", "Arcana"}, cost=4, roles={"ad", "tank"}),
    Champion(name="Taric", traits={"Bastion", "Portal"}, cost=4, roles={"ap", "tank"}),
    Champion(name="Tristana", traits={"Blaster", "Faerie"}, cost=2, roles={"ad"}),
    Champion(name="Twitch", traits={"Frost", "Hunter"}, cost=1, roles={"ad"}),
    Champion(name="Varus", traits={"Blaster", "Pyro"}, cost=4, roles={"ad"}),
    Champion(name="Veigar", traits={"Mage", "Honeymancy"}, cost=3, roles={"ap"}),
    Champion(name="Vex", traits={"Mage", "Chrono"}, cost=3, roles={"ap", "tank"}),
    Champion(name="Warwick", traits={"Frost", "Vanguard"}, cost=1, roles={"ad"}),
    Champion(name="Wukong", traits={"Druid"}, cost=3, roles={"ad", "tank"}),
    Champion(name="Xerath", traits={"Arcana", "Ascendant"}, cost=5, roles={"ap"}),
    Champion(name="Ziggs", traits={"Honeymancy", "Incantor"}, cost=1, roles={"ap"}),
    Champion(name="Zilean", traits={"Preserver", "Chrono"}, cost=2, roles={"ap"}),
    Champion(name="Zoe", traits={"Witchcraft", "Scholar", "Portal"}, cost=1, roles={"ap"}),
]